[parity]
base_path = "/data"
db_path = "/chain"
keys_path = "/config/keys"
chain = "/config/chain.json"

[account]
password = ["/config/password"]

[network]
bootnodes = [
    "enode://2896ad0af42ec57f8bee22dd0933a92b56b17ea34a26f4332c4f0a1cd331f9543e92986db3e335d1cd77e41d37412e324dd2c11ae8147137244d39f5f6662839@172.16.0.10:30303",
    "enode://26a74ca06b3f8f126aa1d0b2ae52e602fe32ee94d3179f30b57efafd7a0fcfbe205c3813496a9efb51d9831d4977dd16d655bcbab08966cb5eb3a22e7830a4f9@172.16.0.11:30303",
    "enode://eff6f23c22ee7797ce0cbfcffcc26edcf14ef7182d812d0ddf0bebe60ddea738dfefaa504d45957d4b28146023cf0346d96125e1b69f18e6c07f2c0b5fe02a76@172.16.0.12:30303",
]

[rpc]
disable = false
interface = "local"
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]

[websockets]
disable = false
port = 8546
interface = "local"
origins = ["none"]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]
hosts = ["none"]

[mining]
force_sealing = true
reseal_on_txs = "all"
refuse_service_transactions = false
usd_per_tx = "0"